//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int ID_PH { get; set; }
        public int ID { get; set; }
        public string Caption { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<System.DateTime> DateOfUpdating { get; set; }
        public Nullable<System.DateTime> DateOfModification { get; set; }
    
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
