//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__ModifiedData
    {
        public int ID { get; set; }
        public int Type { get; set; }
        public Nullable<int> ID01 { get; set; }
        public Nullable<int> ID02 { get; set; }
    }
}
