//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__Renaming01
    {
        public int ID_PI { get; set; }
        public string Name_PI { get; set; }
        public Nullable<int> ID_AB { get; set; }
        public string Name_AB { get; set; }
    }
}
