//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatesOfTransfer
    {
        public int ID_PH { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DateOfUpdating { get; set; }
    }
}
