//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfChangesOfPrice
    {
        public int ID { get; set; }
        public int IDOfDrugstore { get; set; }
        public int IDOfProduct { get; set; }
        public int ModificationOfPrice { get; set; }
        public decimal ModifiedPrice { get; set; }
        public System.DateTime DateOfChange { get; set; }
    
        public virtual ModificationsOfPrice ModificationsOfPrice { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
        public virtual Product Product { get; set; }
    }
}
