//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfReception
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistoryOfReception()
        {
            this.ReportsOfImportingOfPriceLists = new HashSet<ReportsOfImportingOfPriceList>();
        }
    
        public int ID_PH { get; set; }
        public int ID { get; set; }
        public bool ContainsPriceList { get; set; }
        public bool ContainsAnnouncements { get; set; }
        public System.DateTime DateOfReception { get; set; }
        public System.DateTime LocalDateOfSending { get; set; }
    
        public virtual Pharmacy Pharmacy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportsOfImportingOfPriceList> ReportsOfImportingOfPriceLists { get; set; }
    }
}
