//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadedProduct
    {
        public int ID { get; set; }
        public int ID_PG { get; set; }
        public string Name { get; set; }
        public string Composition { get; set; }
        public string Description { get; set; }
    }
}
