//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewInhalersComparison
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IDOf086 { get; set; }
        public int D { get; set; }
        public int E { get; set; }
    }
}
