//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREP_ZDOROVO_COMPARISONS
    {
        public Nullable<int> IDOfExternalProduct { get; set; }
        public string NameOfExternalProduct { get; set; }
        public Nullable<int> IDOfProduct { get; set; }
        public byte ExistsInPriceList { get; set; }
        public byte Compare { get; set; }
    }
}
