//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_group
    {
        public int Id_product_group { get; set; }
        public string Name_full { get; set; }
        public Nullable<System.DateTime> Date_upd { get; set; }
        public bool Is_deleted { get; set; }
    }
}
