//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.HistoryOfChangesOfPrices = new HashSet<HistoryOfChangesOfPrice>();
            this.HistoryOfSearchRequests = new HashSet<HistoryOfSearchRequest>();
        }
    
        public int Id_Product { get; set; }
        public string Name_full { get; set; }
        public Nullable<bool> Is_available { get; set; }
        public string Composition { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_upd { get; set; }
        public int Id_product_group { get; set; }
        public bool Is_deleted { get; set; }
        public Nullable<int> LastGroupOfProduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOfChangesOfPrice> HistoryOfChangesOfPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOfSearchRequest> HistoryOfSearchRequests { get; set; }
    }
}
