//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecodingIDsOfDrugstoresOfImporting
    {
        public System.Guid ID { get; set; }
        public string NameOfDrugstoreOfImporter { get; set; }
        public System.Guid IDOfPrivateImportings { get; set; }
        public int IDOfImporter { get; set; }
        public int IDOfSystem { get; set; }
    
        public virtual PrivateImporting PrivateImporting { get; set; }
    }
}
