//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationOfDrugstore
    {
        public int ID_PH { get; set; }
        public int ID { get; set; }
        public string PathToFolderOfPriceLists { get; set; }
        public string MaskOfFullPriceList { get; set; }
        public string MaskOfIncomingPriceList { get; set; }
        public string MaskOfSoldPriceList { get; set; }
        public Nullable<bool> UseOfIDOfPriceList { get; set; }
        public Nullable<bool> NotDeletingPriceList { get; set; }
        public System.DateTime DateOfUpdating { get; set; }
    }
}
