//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportsOfImportingOfPriceList
    {
        public int ID_PH { get; set; }
        public int ID_HR { get; set; }
        public int CountNotConfirmed { get; set; }
        public int CountOfAdditions { get; set; }
        public int CountOfUnAdditions { get; set; }
        public int CountOfChanges { get; set; }
        public int CountOfUnChanges { get; set; }
        public int CountOfDeletings { get; set; }
        public int CountOfAllPrices { get; set; }
        public bool FullPriceList { get; set; }
    
        public virtual HistoryOfReception HistoryOfReception { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
